services:
  test:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: test
    # network_mode: "host"
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    ports:
      - "7123:5000"
    volumes:
      - .:/app
    command: sleep infinity # Use to spin up a persistent container to exec